export const POSITIVE_TIPS = [
  "O sucesso financeiro não é sobre quanto você ganha, mas sobre como você gerencia o que tem.",
  "Independência financeira é a liberdade de ser você mesmo.",
  "Não poupe o que sobra depois de gastar, gaste o que sobra depois de poupar.",
  "O hábito de poupar é em si uma ferramenta de educação financeira.",
  "Invista em si mesmo. É o melhor investimento que você pode fazer.",
  "Cuidado com as pequenas despesas; um pequeno vazamento pode afundar um grande navio.",
  "Riqueza é a habilidade de experimentar a vida plenamente.",
  "O dinheiro é um mestre terrível, mas um servo excelente.",
  "A melhor época para plantar uma árvore foi há 20 anos. A segunda melhor é agora.",
  "Planejar é trazer o futuro para o presente para que você possa fazer algo a respeito agora.",
  "Viva como ninguém quer viver agora, para que você possa viver como ninguém pode viver depois.",
  "A disciplina é a ponte entre metas e realizações.",
  "Sua renda atual não determina sua riqueza futura, seus hábitos sim.",
  "Frugalidade não é sobre gastar menos, é sobre gastar melhor.",
  "O maior risco é não correr risco nenhum.",
  "Tempo é mais valioso que dinheiro. Você pode conseguir mais dinheiro, mas não mais tempo.",
  "A paciência é um elemento-chave do sucesso financeiro.",
  "Cada real poupado é um funcionário que trabalha para você.",
  "Não compare o seu começo com o meio de outra pessoa.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "A inteligência financeira é a solução de problemas financeiros.",
  "O segredo de progredir é começar.",
  "Mantenha o foco nos seus objetivos, não nos obstáculos.",
  "Acredite que você pode e você já está no meio do caminho.",
  "Organização é a base para a liberdade.",
  "Cada passo, por menor que seja, te aproxima da sua meta.",
  "Seja o dono do seu dinheiro, não o escravo dele.",
  "Educação financeira é um passaporte para o futuro.",
  "Transforme seus sonhos em planos, e seus planos em realidade.",
  "A consistência supera a intensidade no longo prazo.",
  "Valorize o processo, a chegada será apenas uma consequência.",
  "Sua mente é seu maior ativo. Treine-a bem.",
  "O equilíbrio é a chave para uma vida financeira saudável.",
  "Não compre o que você não precisa com dinheiro que você não tem.",
  "Pense no seu 'eu' do futuro com carinho.",
  "A gratidão torna o que temos em suficiente.",
  "Metas são sonhos com prazos determinados.",
  "Construa seu império tijolo por tijolo.",
  "A liberdade começa quando você para de tentar impressionar os outros.",
  "Invista com sabedoria, colha com alegria.",
  "O melhor investimento é aquele que te traz paz mental.",
  "Simplifique sua vida e multiplique seus resultados.",
  "O futuro que você deseja depende do que você faz hoje.",
  "Seja paciente. Coisas boas levam tempo para crescer.",
  "Abra mão do bom para alcançar o excelente.",
  "O conhecimento é o único bem que ninguém pode te tirar.",
  "Você é capaz de realizar mais do que imagina.",
  "Pequenas vitórias diárias constroem grandes destinos.",
  "Mantenha a calma e siga seu planejamento.",
  "A atitude é tudo quando se trata de superar limites.",
  "Celebre cada conquista, não importa o tamanho."
];
